version: 0.2

phases:
  build:
    commands:
      - echo Enter the building phase
      - mvn clean install
  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - target/test-beanstalk.jar
  discard-paths: yes